### ISSUE TITLE
ImportError: No module named pysimpledmx

### ISSUE THREAD

**Issue by LypticPVP** [c0z3n/pySimpleDMX#10]
After running pip install pysimpledmx i'm getting the error:
ImportError: No module named pysimpledmx

In my site-packages folder there is one folder called: pysimpledmx-0.1.0-py2.7.egg-info
But inside it contains no .py files

Probably a beginner python mistake.

Thanks for help :)

**Comment by theDrGray** [comment]
Having the exact same issue on Windows 10 with the new structure. My older, working version on OSX is name simply pysimpledmx and only has py files.

**Comment by nickpetty** [comment]
Same here on OSX El Capitan.

**Comment by nickpetty** [comment]
Fixed in pull request.

**Comment by LypticPVP** [comment]
Can you please fork it so we can use your version for now?

**Comment by nickpetty** [comment]
I have. https://github.com/nickpetty/pySimpleDMX

**Comment by nickpetty** [comment]
Be sure to install with 'python setup.py install', not pip of course.

**Comment by c0z3n** [comment]
Hey all, sorry for being a bit AWOL, and thanks for taking care of this.

**Comment by c0z3n** [comment]
I have uploaded the changes to pypi and added a new release to the repo, so I'm going to consider this closed for now. Thanks again!

**Comment by nickpetty** [comment]
Great! Thanks and no problem!
