### ISSUE TITLE
Convert to Python Package

### ISSUE THREAD

**Issue by saulshanabrook** [c0z3n/pySimpleDMX#6]
Would you consider creating a package for this code by adding a `setup.py` and uploading it to `PyPi`?

It would be easier to be able to `pip install pysimpledmx` instead of having to download the file.

I would be happy to send a pull request with the needed files, if that is the hold up.

**Comment by c0z3n** [comment]
I absolutely would do this. If you send the pull request, I'll make sure it gets on pypi.

**Comment by c0z3n** [comment]
package is available on pypi! thanks for prepping it for upload.

**Comment by saulshanabrook** [comment]
:)
